tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/php'
tap 'neovim/neovim'
tap 'sanemat/font'
brew 'coreutils'
brew 'curl'
brew 'git'
brew 'fzf'
brew 'git-flow'
brew 'gnu-tar'
brew 'htop'
brew 'mas'
brew 'mysql'
brew 'nginx'
brew 'python3'
brew 'sshrc'
brew 'the_silver_searcher'
brew 'tree'
brew 'vim', args: ['with-lua']
brew 'watch'
brew 'wget'
brew 'zsh', args: ['without-etcdir']
brew 'homebrew/php/php71'
brew 'homebrew/php/composer'
brew 'neovim/neovim/neovim'
brew 'sanemat/font/ricty'
cask 'appcleaner'
cask 'iterm2'
cask 'google-chrome'
cask 'sequel-pro'
cask 'sourcetree'
cask 'google-japanese-ime'
cask 'spectacle'
cask 'virtualbox'
cask 'keepassx'
cask 'sublime-text'
cask 'alfred'
cask 'astah-community'
cask 'xmind'
cask 'skype'
cask 'thunderbird'
cask 'firefox'
cask 'filezilla'
cask 'dropbox'
cask 'mysqlworkbench'
cask 'p4merge'
cask 'vlc'
cask 'sqlitebrowser'
cask 'evernote'
cask 'table-tool'
mas 'LINE', id: 539883307
mas 'Xcode', id: 497799835
mas 'Memory Clean 2', id: 1114591412

