tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "mackerelio/mackerel-agent"
tap "neovim/neovim"
tap "sanemat/font"
tap "shyiko/kubesec"
brew "ansible"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "curl"
brew "fish"
brew "fzf"
brew "git"
brew "git-flow"
brew "git-lfs"
brew "gnu-tar"
brew "graphviz"
brew "homebrew/core/composer"
brew "htop"
brew "iproute2mac"
brew "kube-ps1"
brew "kubectx"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "mackerelio/mackerel-agent/mkr"
brew "mas"
brew "mcrypt"
brew "memcached"
brew "mkr"
brew "mysql"
brew "neovim/neovim/neovim"
brew "nginx"
brew "packer"
brew "packer-completion"
brew "phpunit"
brew "python3"
brew "shyiko/kubesec/kubesec"
brew "sshrc"
brew "stern"
brew "tfenv"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"#, args: ["with-lua"]
brew "watch"
brew "wget"
brew "zsh"#, args: ["without-etcdir"]
cask "alfred"
cask "appcleaner"
# cask "awscli"
cask "chatwork"
cask "clipy"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "google-japanese-ime-dev"
cask "iterm2"
cask "java"
cask "java6"
cask "keepassx"
cask "mi"
cask "mysqlworkbench"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "sourcetree"
cask "spectacle"
cask "station"
cask "sublime-text"
cask "table-tool"
cask "the-unarchiver"
# cask "virtualbox" エラーになるのでコメントアウト
cask "vlc"
cask "xmind"
# cask "astah-community"
# cask "evernote"
# cask "filezilla"
# cask "franz"
# cask "insomniax"
# cask "java7"
# cask "p4merge"
# cask "simple-comic"
# cask "sqlitebrowser"
# cask "thunderbird"
# masはApple Storeのログインしてから出ないとエラーになる
mas "LINE", id: 539883307
mas "Memory Clean 2", id: 1114591412
mas "Xcode", id: 497799835
