# mise グローバル設定
# https://mise.jdx.dev/configuration.html

[tools]
go = "1.26.0"
node = "25.6.1"
pnpm = "10.26.2"
python = "3.14.3"
terraform = "1.14.5"
terragrunt = "0.99.3"
uv = "0.10.4"

[settings]
# 実験的機能を無効化
experimental = false
# ツールがない場合に自動インストール
auto_install = true
go_set_goroot = false
