#!/bin/bash
# AI 指示ファイルを ai/rules/ から生成する
#
# 共通ルール（common.md）とツール固有ルールを結合し、各ツールが読むファイルを出力する。
# 各ツールは自分のファイルを読むだけで完結するため、エージェントの挙動は変わらない。
#
# 生成対象を直接編集しても本スクリプトの実行で上書きされる。
# 変更は ai/rules/ 配下に対して行い、その後 `bash ai/rules/build.sh` を実行する。
set -e
set -u

RULES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$RULES_DIR/../.." && pwd)"

BANNER="<!-- Generated by ai/rules/build.sh - DO NOT EDIT DIRECTLY. Edit ai/rules/ and run: bash ai/rules/build.sh -->"

# 相互リンクを出力する
# $1: リポジトリルートへの相対プレフィックス, $2: 自分自身のファイル名
emit_references() {
    local prefix="$1"
    local self="$2"

    echo ""
    echo "---"
    echo ""
    echo "## References"
    echo ""
    echo "- **Project Overview / Quick Start**: [README.md](${prefix}README.md)"
    if [ "$self" != "CLAUDE.md" ]; then
        echo "- **Claude Code Guidelines**: [CLAUDE.md](${prefix}CLAUDE.md)"
    fi
    if [ "$self" != "AGENTS.md" ]; then
        echo "- **Codex / Agent Guidelines**: [AGENTS.md](${prefix}AGENTS.md)"
    fi
    if [ "$self" != "GEMINI.md" ]; then
        echo "- **Gemini Guidelines**: [GEMINI.md](${prefix}GEMINI.md)"
    fi
    if [ "$self" != "CURSOR.mdc" ]; then
        echo "- **Cursor Rules**: [CURSOR.mdc](${prefix}.cursor/rules/CURSOR.mdc)"
    fi
}

# 指示ファイルを1つ生成する
# $1: 出力パス（ROOT_DIR 相対）, $2: 見出し, $3: 導入文,
# $4: 固有ルールファイル名, $5: ルートへの相対プレフィックス
generate() {
    local out="$ROOT_DIR/$1"
    local title="$2"
    local intro="$3"
    local specific="$4"
    local prefix="$5"
    local self
    self="$(basename "$1")"
    local tmp
    tmp="$(mktemp)"

    {
        echo "# $title"
        echo ""
        echo "$BANNER"
        echo ""
        echo "$intro"
        echo ""
        echo "---"
        echo ""
        cat "$RULES_DIR/common.md"
        if [ -s "$RULES_DIR/$specific" ]; then
            echo ""
            echo "---"
            echo ""
            cat "$RULES_DIR/$specific"
        fi
        emit_references "$prefix" "$self"
    } >"$tmp"

    # common.md 内のリンクはリポジトリルート基準。
    # .cursor/rules/ 配下だけ階層が深いためプレフィックスを補う。
    if [ -n "$prefix" ]; then
        sed -E "s#\]\((README\.md)\)#](${prefix}\1)#g" "$tmp" >"$tmp.linked"
        mv "$tmp.linked" "$tmp"
    fi

    mkdir -p "$(dirname "$out")"
    mv "$tmp" "$out"
    chmod 644 "$out"
    echo "  ✓ $1"
}

# 生成物を prettier で整形する（npm run format:check を通すため）
format_outputs() {
    local prettier="$ROOT_DIR/node_modules/.bin/prettier"

    if [ ! -x "$prettier" ]; then
        echo "  ⚠ prettier 未配置のため整形をスキップ"
        echo "    npm install 後に npm run format を実行してください"
        return
    fi

    (
        cd "$ROOT_DIR"
        "$prettier" --write --log-level warn CLAUDE.md AGENTS.md GEMINI.md
        # .mdc は npm run format の対象外なのでパーサを明示して個別に整形する
        "$prettier" --write --log-level warn --parser markdown .cursor/rules/CURSOR.mdc
    )
    echo "  ✓ prettier で整形"
}

main() {
    echo "AI 指示ファイルを生成..."

    generate "CLAUDE.md" \
        "CLAUDE.md" \
        "This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository." \
        "claude.md" \
        ""

    generate "AGENTS.md" \
        "Agent Guide (AI Standard Agent)" \
        "This file defines **mandatory behavior rules** for AI agents working on the dotfiles project." \
        "codex.md" \
        ""

    generate "GEMINI.md" \
        "GEMINI.md" \
        "This file provides guidance to Gemini / Antigravity when working with code in this repository." \
        "gemini.md" \
        ""

    generate ".cursor/rules/CURSOR.mdc" \
        "Cursor Rules" \
        "This document defines **mandatory rules and constraints** for Cursor when working on the dotfiles project." \
        "cursor.md" \
        "../../"

    format_outputs

    echo ""
    echo "完了. 生成物を確認してコミットしてください:"
    echo "  git diff --stat CLAUDE.md AGENTS.md GEMINI.md .cursor/rules/CURSOR.mdc"
}

main "$@"
