#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  cleanup_tmux_terminal.sh --session <name> [--state-file <path>] [--dry-run]

Options:
  --session <name>      tmux session name (allowed: [A-Za-z0-9._:-])
  --state-file <path>   metadata file generated by open_tmux_terminal.sh
  --dry-run             print cleanup actions without executing
  -h, --help            show this help
USAGE
}

SESSION=""
STATE_FILE=""
DRY_RUN=0

TERMINAL_BACKEND=""
OPEN_MODE=""
WINDOW_CLOSE_SUPPORTED="0"
ITERM_WINDOW_ID=""
TERMINAL_WINDOW_ID=""
GHOSTTY_PID=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --session)
      SESSION="${2:-}"
      shift 2
      ;;
    --state-file)
      STATE_FILE="${2:-}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$SESSION" ]]; then
  echo "--session is required" >&2
  usage >&2
  exit 2
fi

if [[ ! "$SESSION" =~ ^[A-Za-z0-9._:-]+$ ]]; then
  echo "invalid session name: $SESSION" >&2
  exit 2
fi

log() {
  echo "[cleanup_tmux_terminal] $*" >&2
}

warn() {
  echo "[cleanup_tmux_terminal][WARN] $*" >&2
}

load_state_file() {
  local key=""
  local value=""

  if [[ -z "$STATE_FILE" ]]; then
    log "state file was not provided; terminal close step is skipped."
    return 0
  fi

  if [[ ! -f "$STATE_FILE" ]]; then
    warn "state file was not found: $STATE_FILE"
    return 0
  fi

  while IFS='=' read -r key value; do
    value="${value%$'\r'}"
    case "$key" in
      TERMINAL_BACKEND) TERMINAL_BACKEND="$value" ;;
      OPEN_MODE) OPEN_MODE="$value" ;;
      WINDOW_CLOSE_SUPPORTED) WINDOW_CLOSE_SUPPORTED="$value" ;;
      ITERM_WINDOW_ID) ITERM_WINDOW_ID="$value" ;;
      TERMINAL_WINDOW_ID) TERMINAL_WINDOW_ID="$value" ;;
      GHOSTTY_PID) GHOSTTY_PID="$value" ;;
      *) ;;
    esac
  done < "$STATE_FILE"

  case "$TERMINAL_BACKEND" in
    ""|ghostty|iterm2|terminal|current_shell) ;;
    *)
      warn "invalid TERMINAL_BACKEND in state file: $TERMINAL_BACKEND"
      TERMINAL_BACKEND=""
      ;;
  esac

  case "$OPEN_MODE" in
    ""|tab|window|current_shell) ;;
    *)
      warn "invalid OPEN_MODE in state file: $OPEN_MODE"
      OPEN_MODE=""
      ;;
  esac

  case "$WINDOW_CLOSE_SUPPORTED" in
    0|1) ;;
    *)
      warn "invalid WINDOW_CLOSE_SUPPORTED in state file: $WINDOW_CLOSE_SUPPORTED"
      WINDOW_CLOSE_SUPPORTED="0"
      ;;
  esac

  if [[ -n "$ITERM_WINDOW_ID" && ! "$ITERM_WINDOW_ID" =~ ^[0-9]+$ ]]; then
    warn "invalid ITERM_WINDOW_ID in state file: $ITERM_WINDOW_ID"
    ITERM_WINDOW_ID=""
  fi

  if [[ -n "$TERMINAL_WINDOW_ID" && ! "$TERMINAL_WINDOW_ID" =~ ^[0-9]+$ ]]; then
    warn "invalid TERMINAL_WINDOW_ID in state file: $TERMINAL_WINDOW_ID"
    TERMINAL_WINDOW_ID=""
  fi

  if [[ -n "$GHOSTTY_PID" && ! "$GHOSTTY_PID" =~ ^[0-9]+$ ]]; then
    warn "invalid GHOSTTY_PID in state file: $GHOSTTY_PID"
    GHOSTTY_PID=""
  fi
}

kill_tmux_session() {
  if ! command -v tmux >/dev/null 2>&1; then
    warn "tmux command is not available; skipping tmux cleanup."
    return 0
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[DRY-RUN] tmux has-session -t \"$SESSION\" && tmux kill-session -t \"$SESSION\""
    return 0
  fi

  if tmux has-session -t "$SESSION" 2>/dev/null; then
    if ! tmux kill-session -t "$SESSION" 2>/dev/null; then
      warn "failed to kill tmux session: $SESSION"
    fi
  else
    log "tmux session was already absent: $SESSION"
  fi
}

close_ghostty_window() {
  if [[ -z "$GHOSTTY_PID" ]]; then
    warn "Ghostty PID is empty. window close is skipped."
    return 0
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[DRY-RUN] kill -TERM \"$GHOSTTY_PID\""
    return 0
  fi

  if ! kill -0 "$GHOSTTY_PID" 2>/dev/null; then
    warn "Ghostty PID is not running anymore: $GHOSTTY_PID"
    return 0
  fi

  if ! kill -TERM "$GHOSTTY_PID" 2>/dev/null; then
    warn "failed to terminate Ghostty PID: $GHOSTTY_PID"
  fi
}

close_iterm2_window() {
  local stdout=""
  local applescript=""

  if [[ -z "$ITERM_WINDOW_ID" ]]; then
    warn "iTerm2 window id is empty. window close is skipped."
    return 0
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[DRY-RUN] close iTerm2 window id $ITERM_WINDOW_ID"
    return 0
  fi

  applescript=$(cat <<EOF
tell application "iTerm"
    if not (exists window id $ITERM_WINDOW_ID) then
        return "missing"
    end if
    close (window id $ITERM_WINDOW_ID)
    return "closed"
end tell
EOF
)
  if ! stdout="$(osascript -e "$applescript" 2>/dev/null)"; then
    warn "failed to close iTerm2 window id: $ITERM_WINDOW_ID"
    return 0
  fi

  if [[ "$stdout" != "closed" ]]; then
    warn "iTerm2 window was not closed (status: $stdout, id: $ITERM_WINDOW_ID)"
  fi
}

close_terminal_window() {
  local stdout=""
  local applescript=""

  if [[ -z "$TERMINAL_WINDOW_ID" ]]; then
    warn "Terminal.app window id is empty. window close is skipped."
    return 0
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[DRY-RUN] close Terminal.app window id $TERMINAL_WINDOW_ID"
    return 0
  fi

  applescript=$(cat <<EOF
tell application "Terminal"
    if not (exists window id $TERMINAL_WINDOW_ID) then
        return "missing"
    end if
    close (window id $TERMINAL_WINDOW_ID)
    return "closed"
end tell
EOF
)
  if ! stdout="$(osascript -e "$applescript" 2>/dev/null)"; then
    warn "failed to close Terminal.app window id: $TERMINAL_WINDOW_ID"
    return 0
  fi

  if [[ "$stdout" != "closed" ]]; then
    warn "Terminal.app window was not closed (status: $stdout, id: $TERMINAL_WINDOW_ID)"
  fi
}

kill_tmux_session
load_state_file

if [[ "$OPEN_MODE" != "window" ]]; then
  log "open mode is '$OPEN_MODE'; window close is not required."
  exit 0
fi

if [[ "$WINDOW_CLOSE_SUPPORTED" != "1" ]]; then
  warn "window close is not supported for this launch state."
  exit 0
fi

case "$TERMINAL_BACKEND" in
  ghostty)
    close_ghostty_window
    ;;
  iterm2)
    close_iterm2_window
    ;;
  terminal)
    close_terminal_window
    ;;
  current_shell|"")
    log "terminal backend '$TERMINAL_BACKEND' is not closable in this flow."
    ;;
  *)
    warn "unsupported terminal backend: $TERMINAL_BACKEND"
    ;;
esac

exit 0
